chrome.storage.sync.get(['slangOption', 'isEnabled'], function(result) {
    console.log('Get');
    const isEnabled = result.isEnabled;
  
    if (isEnabled) {
      document.addEventListener('click', function(event) {
        console.log('Click');
        const targetElement = event.target;
        try {
            targetElement.textContent = slangify(targetElement.textContent, slangDictionary[result.slangOption]);
        } catch(error) {
            // Handle any errors that occur during slangification
            console.log(error)
        }
      });
    }
  });

  function slangify(text, slangs) {
    const words = text.split(' ');
    const modifiedText = [];
  
    for (const word of words) {
      if (Math.random() < 0.2) {
        const modifiedWord = getRandomSlang(slangs);
        modifiedText.push(modifiedWord);
      }
      modifiedText.push(word);
    }
  
    return modifiedText.join(' ');
  }
  
  function getRandomSlang(slangs) {
    const randomIndex = Math.floor(Math.random() * slangs.length);
    const randomSlang = slangs[randomIndex];
  
    const randomStyle = Math.random();
    if (randomStyle < 0.25) {
      return `"${randomSlang}"`;
    } else if (randomStyle < 0.50) {
      return `(${randomSlang})`;
    } else if (randomStyle < 0.75) {
      return `*${randomSlang}*`;
    } else {
      return randomSlang;
    }
  }

  const slangDictionary = {
    teenage: [
        'lol 😂',
        'bruh 😒',
        'lit 🔥',
        'chill 😎',
        'dope 🤙',
        'sick 🤢',
        'YO 🤟',
        'swag 😎🔥',
        'OMG 😱',
        'WTF 🤯',
        'hella 🤘',
        'squad 🤝',
        'gucci 👌',
        'cray cray 🤪',
        'on fleek 💅',
        'fam 👪',
        'bae ❤️',
        'lit AF 🔥🔥',
        'Slay queen 👑',
        'Savage 😈',
        'Noob 🤓',
        'YOLO 🙌',
        'FOMO 😫',
        'GOAT 🐐',
        'AFK 🚶',
        'Squad goals 🙌💯',
        'Sips tea ☕️',
        'Netflix and chill 🍿📺',
        'Woke 💡',
        'Goals 💪',
        'FOMO 😅',
        'BFF 👯‍♂️',
        'TTYL 👋',
        'IRL 🌍',
        'ICYMI 📺',
        'OOTD 👗',
        'G2G 🏃‍♂️',
        'ICYDK 💡',
        'ROFL 🤣',
        'ILY 💖',
        'STFU 🙊',
        'JK 😜',
        'SMH 🤦‍♀️',
        'TBH 🤷‍♂️',
        'ICYMI 💁‍♀️',
        'OMW 🚗',
        'NBD 😎',
        'YOLO 🌟',
        'GNO 🎉',
        'WYD 🤔',
        'LOLZ 😆',
        'OMG 🙀',
        'LMAO 😂',
        'Squad up 🤝',
        'On point 👌',
        'Turnt up 🎉',
        'Chillaxin 😌',
        'Hakuna matata 🦁',
        'Hype AF 🙌💯',
        'Lituation 🎆',
        'Yasss queen 👑🙌',
        'Can\'t even 😫',
        'Totes adorbs 😍',
        'No chill ❄️',
        'Let\'s bounce 🏀',
        'Shooketh 😱',
        'Feeling blessed 🙏',
        'Werk it 👠',
        'Living my best life 🌟',
        'FOMO is real 😅',
        'Stay woke 💡',
        'Savage AF 😈',
        'Squad goals on fleek 🙌💯',
        'Posi vibes only ✨',
        'Adulting is hard 🙃',
        'Feelin\' myself 😎💁‍♀️',
        'Sorry not sorry 🤷‍♀️',
        'Doing the most 💁‍♂️',
        'Can\'t even deal with this 🙅‍♀️',
        'Blessed and highly favored 🙏✨',
        'Living my truth 💯🌟'
  ],

    cowboy: [
    'yeehaw',
    'pardner',
    'howdy',
    'giddy up',
    'reckon',
    'holler',
    'varmint',
    'wrangler',
    'roundup',
    'saddle up',
    'outlaw',
    'spur',
    'lasso',
    'buckaroo',
    'hoedown',
    'cowpoke',
    'hitching post',
    'hoss',
    'rustler',
    'range',
    'trailblazer',
    'barnstormer',
    'buckskin',
    'cowboy up',
    'galoot',
    'tumbleweed'
  ],
rapper:  [
    'yo',
    'dope',
    'lit',
    'chill',
    'phat',
    'bling',
    'flow',
    'homie',
    'grind',
    'hustle',
    'ballin\'',
    'flex',
    'trippin\'',
    'fresh',
    'fly',
    'ill',
    'crunk',
    'stacks',
    'boss',
    'fire',
    'mic drop',
    'trap',
    'beats',
    'rhyme',
    'stuntin\'',
    'hype'
  ], 
kikoolol: [
    'mdr',
    'ptdr',
    'slt',
    'trop cool',
    'tro stylé',
    'grave',
    'wsh',
    'bg',
    'tmtc',
    'tg',
    'jpp',
    'lolilol',
    'trop mignon',
    'xD',
    'pdp',
    'c tro marrant',
    'tro lol',
    'tro stylayyyyy',
    'omgggg',
    'wtf',
    'haha',
    'pétage de plomb',
    'tro chou',
    'mdr mdr mdr',
    'kikoo',
    'trop ouf'
  ],
ravage: [
    'ptn',
    'bg',
    'XDDDDD',
    'hap',
    'tg',
    'mdr',
    'lol',
    'fdp',
    'c tro',
    'kikoo',
    '?????????',
    'nrv',
    'oupas',
    'tro for',
    'tro stylé',
    'c ouf',
    'rohff',
    'lolilol',
    'c tro d4rk',
    'chelou',
    'ouf malade',
    'grave ou pas',
    'tro de la balle',
    'wesh gros',
    'tro choquant',
    'miskine'
  ],
surfer: [
    'stoked',
    'gnarly',
    'dude',
    'rad',
    'hang loose',
    'shreddin\'',
    'tubular',
    'cowabunga',
    'epic',
    'wipeout',
    'chillaxin\'',
    'beach bum',
    'wave rider',
    'salty'
  ],
valleyGirl: [
    'like',
    'totally',
    'OMG',
    'gag me with a spoon',
    'whatever',
    'for sure',
    'like, seriously?',
    'like, no way',
    'like, awesome',
    'like, I can\'t even',
    'like, OMG, like, totally!',
    'like, totes',
    'like, OMG, like, gag me!'
  ],
pirate: [
    'arrr',
    'matey',
    'landlubber',
    'scallywag',
    'ahoy',
    'booty',
    'avast',
    'plunder',
    'ye',
    'grog',
    'plunderin\'',
    'Jolly Roger',
    'swashbucklin\'',
    'scurvy dog'
  ],
gamer: [
    'pwned',
    'noob',
    'GG (good game)',
    'epic fail',
    'respawn',
    'pwnage',
    'frag',
    'leet',
    'camper',
    'headshot',
    'lag',
    'AFK (away from keyboard)',
    'rekt',
    'power-up'
  ],
peppa: [
    'oink',
    'muddy puddles',
    'snort',
    'splish splash',
    'daddy pig',
    'mummy pig',
    'George',
    'Peppa',
    'Grampy Rabbit',
    'Grandpa Pig',
    'Grandma Pig',
    'snorts and giggles',
    'jumping in puddles',
    'oink-tastic',
    'pigtastic',
    'piggy fun',
    'family time',
    'adventure',
    'oinktastic',
    'silly pig',
    'happy snorts',
    'hooves up',
    'peppasode',
    'peppa-mania',
    'oinkalicious',
    'snorty laughs',
    'fun-filled',
    'snorting good time',
    'oinktastic adventures',
    'splashing about',
    'muddy oinkers',
    'peppa party',
    'oinkers delight',
    'snorty snuggles',
    'peppa-mazing',
    'giggles galore',
    'oinked out',
    'jumping with joy',
    'happily snorting',
    'playtime oinks',
    'snorts of laughter',
    'peppa\'s world',
    'piggy perfection'
],
twitch: [
    'PogChamp',
  'Kappa',
  'Poggers',
  'LUL',
  'EZ Clap',
  'OMEGALUL',
  'FeelsBadMan',
  'FeelsGoodMan',
  'MonkaS',
  'PepeHands',
  'TriHard',
  'KKona',
  'BlessRNG',
  'RIP',
  'GG',
  'WutFace',
  'POGGIES',
  '5Head',
  'SourPls',
  'NotLikeThis',
  'MingLee',
  'FailFish',
  'HeyGuys',
  'SwiftRage',
  'Keepo',
  'VoHiYo',
  'ResidentSleeper',
  'PogU',
  'WideHardo',
  'LULW',
  'PepeLaugh',
  'EZ',
  'EZPZ',
  'HYPE',
  'Savage',
  'Lit',
  'YOLO',
  'Epic',
  'Clutch',
  'Gamer',
  'Streamer',
  'PogMaster',
  'ChatGod',
  'Banhammer',
  'ClipThat',
  'PogOff',
  'Noob',
  'GGEZ',
]}
